Package: lua
Version: 5.1.4
Revision: 3
Maintainer: Marmalade Package Team <packages@ideaworkslabs.com>
Mkbs: lua.mkf
Libraries: lua
Description: |
 zlib library for creating and reading zlib compressed data.
Contents:
 - upstream/src/lua.h : h/lua.h
 - upstream/src/luaconf.h : h/luaconf.h
 - upstream/src/lualib.h : h/lualib.h
 - upstream/src/lauxlib.h : h/lauxlib.h
Contents-Source:
 - README.txt
 - data/app.icf
 - lua.mkf
 - lua.mkb
 - upstream/src/lauxlib.c
 - upstream/src/linit.c
 - upstream/src/liolib.c
